version: '3.8'

services:
  magento:
    build: ./
    working_dir: /app
    depends_on:
      - redis
      - mariadb
      - elasticsearch
    volumes:
      - ./:/app
    ports:
      - 80:80
    environment:
      - MAGENTO_RUN_MODE=developer
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=secret
      - ES_HOSTS=opensearch:9200

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379

  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch
      - discovery.seed_providers=file
      - disable_password_auth=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
