on:
  workflow_call:
    inputs:
      application_name:
        description: 'The name of the application'
        type: string
      application_version:
        description: 'The version of the application'
        type: string
      environment:
        description: 'The environment to deploy to'
        type: string
      registry_name:
        description: 'The name of the Azure container registry'
        type: string
    secrets:
      AZURE_AD_TENANT_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Secret Value
        run: echo ${{ secrets.AZURE_CLIENT_ID }}  
      #- name: Log in to Azure using OIDC
      #  uses: azure/login@v1
      #  with:
      #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #    tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
      #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#      - name: Show account info (for debugging)
 #       run: | 
  #        az account show
   #       az group list
