on:
  workflow_call:
    inputs:
      application_name:
        description: 'The name of the application'
        type: string
      application_version:
        description: 'The version of the application'
        type: string
      environment:
        description: 'The environment to deploy to'
        type: string
      registry_name:
        description: 'The name of the Azure container registry'
        type: string
    secrets:
      AZURE_AD_TENANT_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: 50dff3c5-4049-43ef-a2ca-898b69d6dbb5
          tenant-id: c23dfd33-3b09-4165-8ce6-d7f78fe81511
          subscription-id: 5d0550fd-2351-46e3-8aad-705e21e1673e

      - name: Show account info (for debugging)
        run: | 
          az account show
          az group list
