name: Deploy Application

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  id-token: write
  contents: read

jobs:
  deploy_test:
    uses: ./.github/workflows/deploy.yml
    name: Deploy to Test
    if: github.ref_type == 'branch'
    with:
      application_name: magento246-test
      application_version: ${{ github.sha }}
      environment: Test
      registry_name: magento246test
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy_prod:
    uses: ./.github/workflows/deploy.yml
    name: Deploy to Production
    if: github.ref_type == 'tag'
    with:
      application_name: magento246-test
      application_version: ${{ github.ref_name }}
      environment: Production
      registry_name: northwindplaytest
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
